### ISSUE TITLE
Does not seem to integrate with Woocommerce Memberships

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscriptions-gifting#169] opened 2016-10-04 18:32 UTC
From @EneHacheCe on https://github.com/Prospress/woocommerce-subscriptions-gifting/pull/168#issuecomment-251424245:

> I'm trying to use the plug in, but it does not seem to integrate with Woocommerce Memberships. The subscription appears for the user who receives the gift, but no membership is associated. My current WCM version is 1.6.5. Did I miss any configuration steps? How can I start debugging this? Thanks!

**Comment by thenbrent** [comment] 2016-10-04 18:35
Hi @EneHacheCe there are no known issues with WooCommerce Memberships and the integration was recently tested.

Can you please copy/paste your WooCommerce System Status report here so we can look into it further. There is more information on the System Status report here: https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/

Feel free to remove any personal or sensitive information from that first, like site URL.

**Comment by EneHacheCe** [comment] 2016-10-04 18:47
Hello @thenbrent! Thanks for crating the issue. Here's my System Status report:

### WordPress Environment ###

Home URL: http://################.local
Site URL: http://################.local
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.19 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (40) ###

Accordions: by pickplugins – 2.0.13
Advanced Cron Manager: by Kuba Mikita – 1.4.3
Advanced Custom Fields Pro: by elliot condon – 5.2.7
Backup: by Backup Guard – 1.1.20
Better Search Replace: by Delicious Brains – 1.2.10
Cast from Vimeo: by NHC – 1.0
######### GeoIP Redirect: by  – 0.7
Geoip Video Restrictions: by  – 0.1
######### - Subsbribe to blog: by enehachece – 1.0
######### - WooCommerce Salesforce CRM Integration: by Hungnam – 1.0
Conditional Menus: by Themify – 1.0.6
Custom Post Type UI: by WebDevStudios – 1.4.1
Duplicate Post: by Enrico Battocchi – 2.6
Duplicator: by LifeInTheGrid – 1.1.16
Font Awesome 4 Menus: by New Nine Media – 4.6.3.3
Gallery: by Huge-IT – 2.0.2
GeoIP Detection: by Yellow Tree (Benjamin Pick) – 2.5.7
If Menu: by Andrei Igna – 0.6
Noindex Pages: by Radley Sustaire – 1.0.1
Social Login: by Claude Schlesser – 5.2
Page scroll to id: by malihu – 1.6.1
Plancha Dump: by NHC – 1.0
Recent Posts Widget With Thumbnails: by Martin Stehle – 4.13
Redirection: by John Godley – 2.4.5
WP REST API: by WP REST API Team – 2.0-beta13.1
Show Current Template: by JOTAKI Taisuke – 0.2.2
Simple Pull Quote: by Toby Cryns – 1.5
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce MailChimp Integration: by WooThemes – 1.0.1
WooCommerce Memberships: by WooThemes / SkyVerge – 1.6.5 – 1.7.0 is available
WooCommerce Subscriptions Gifting: by Prospress Inc. – 1.0
WooCommerce Subscriptions: by Prospress Inc. – 2.0.19 – 2.0.20 is available
WooCommerce: by WooThemes – 2.6.4
WooCommerce Helper: by WooCommerce – 1.7.1
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 3.5
WP CSV: by CPK Web Solutions – 1.8.0.0
Email Login: by Beau Lebens – 4.6.4
wpMandrill: by Mandrill – 1.33
Related Posts Yuzo: by iLen – 5.12.51

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page not set
Cart: #2413 - /cart/
Checkout: #2414 - /checkout/
My Account: #2415 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: ######### Theme v2.1
Version: 2.0.0
Author URL: #############################
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 2.7.3
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: #########-v2/woocommerce/cart/cart-empty.php
#########-v2/woocommerce/checkout/form-billing.php
#########-v2/woocommerce/checkout/payment.php
#########-v2/woocommerce/checkout/review-order.php
#########-v2/woocommerce/checkout/thankyou.php
#########-v2/woocommerce/content-single-product.php
#########-v2/woocommerce/emails/customer-completed-order.php
#########-v2/woocommerce/emails/customer-new-account.php
#########-v2/woocommerce/myaccount/dashboard.php
#########-v2/woocommerce/myaccount/form-edit-account.php
#########-v2/woocommerce/myaccount/form-edit-address.php
#########-v2/woocommerce/myaccount/form-lost-password.php
#########-v2/woocommerce/notices/error.php
#########-v2/woocommerce/notices/success.php
#########-v2/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
#########-v2/woocommerce/single-product.php

**Comment by james-allan** [comment] 2016-10-05 01:08
Hi @EneHacheCe,

I can't initially see anything from your system status that would cause memberships not be granted correctly. I've just tested memberships integration again locally and it works fine for me at least so could you elaborate on your initial report slightly? 

ie.
> The subscription appears for the user who receives the gift, but no membership is associated. 

Is the membership not being created at all or is it being granted to the purchaser not the recipient? 

Could you also provide us with further details about how you are testing this? Does your cart contain multiple memberships products or does the customer or recipient user already have a membership to that plan for example.

**Comment by EneHacheCe** [comment] 2016-10-05 14:16
Hello, James!
The cart contains one Subscription Product (of a certain variation). The user is created at the time of checkout (this membership is the only thing we sell so, until now, there was no reason for us to have a user without a subscription+membership).

When I try to buy a subscription as a gift:
- Both users (recipient and buyer) are created
![selection_054](https://cloud.githubusercontent.com/assets/13087985/19116448/f85156ce-8aeb-11e6-980e-df6110f62216.png)
- An active subscription is created:  "#6064 for **Enehachece100503** purchased by **Nath 100503 Gives a Gift**"
- No membership is created

So, the subscription looks like this:
![selection_053](https://cloud.githubusercontent.com/assets/13087985/19116486/137b4162-8aec-11e6-8010-1016ec695e86.png)

Whereas a subscription (same variation) that you buy for yourself looks like this:
![selection_051](https://cloud.githubusercontent.com/assets/13087985/19116535/3f210162-8aec-11e6-9994-56a285da6052.png)

**Comment by EneHacheCe** [comment] 2016-10-05 14:31
I've written error_logs all over the place, and i've seen that in woocommerce-memberships.php (WCM plugin) the method "get_access_granting_purchased_product_ids" returns the id only when you are buying the subscription for yourself. When you buy it as a gift it returns nothing.

Also (possibly off-topic) if I go to WooCommerce / Membership Plans / My Membership Plan and click the Grant Access button, all the memberships are created and assigned to the buyers, not the recipients. I don't know if this is expected behaviour.

**Comment by lkraav** [comment] 2016-10-05 18:45
> Also (possibly off-topic) if I go to WooCommerce / Membership Plans / My Membership Plan and click the Grant Access button, all the memberships are created and assigned to the buyers, not the recipients. I don't know if this is expected behaviour.

I've also wondered if it would make sense for this button to have a "dry-run" checkbox beneath it. I'm scared to click it, because should it do something wrong, I'm in for an expensive mess. Alternatively it should be a 2-step process - "report what I'm about to do first, then confirm".

Not planning to hijack this thread, but wanted to get it written down before I forget.

**Comment by james-allan** [comment] 2016-10-06 03:40
Hi @EneHacheCe.

Thanks for those thorough details.

I tried to replicate the behaviour you're seeing by following the steps you provided to the t. However in my case, a membership was correctly granted to the recipient. I also error logged the ids returned by `get_access_granting_purchased_product_ids` and in both cases (gifting and purchasing without a recipient) and got a product id in both cases.

In this screenshot you provided: 

![screen shot 2016-10-06 at 12 04 29 pm](https://cloud.githubusercontent.com/assets/8490476/19138258/d28bc708-8bbd-11e6-940f-d15c24de461b.png)

You've highlighted in yellow that there are no active memberships. This field is added by WCM to display the active memberships the `$subscription->customer_user` (purchaser) has. This is why in this case it is displaying none. I'll have a chat to the SkyVerge team to see what we can do within Gifting to correct this. In the meantime can you check if the recipient's membership is listed in the table at **WooCommerce->Memberships**? If the membership isn't listed there we will need to continue debugging.

For a comparison, in case I've missed something, here are some screenshots from my testing: https://cloudup.com/cwUPzHLVq3B

-------
> if I go to WooCommerce / Membership Plans / My Membership Plan and click the Grant Access button, all the memberships are created and assigned to the buyers, not the recipients. I don't know if this is expected behaviour.

👍  This is a good point, I've opened #170 to address that.

---- 
> I've also wondered if it would make sense for this button to have a "dry-run" checkbox beneath it. I'm scared to click it, because should it do something wrong, I'm in for an expensive mess.

@lkraav You should report this to the SkyVerge team through a support ticket, because that button is part of the Memberships Plugin it is beyond the reach of Gifting to address that.

**Comment by EneHacheCe** [comment] 2016-10-06 13:24
Thank you! There is no new membership listed in **WooCommerce->Memberships** :(

**Comment by EneHacheCe** [comment] 2016-10-06 14:54
Hey, I think I've found where it fails for me:
In **WCSG_Memberships_Integration::get_user_unique_membership_access_granting_product_ids**
$order->get_items() returns an array with the variation id
$all_access_granting_product_ids is an array with the product id

So this:
`foreach ( $order->get_items() as $order_item_id => $order_item ) {
				if ( in_array( wcs_get_canonical_product_id( $order_item ), $all_access_granting_product_ids ) ) {
					//this never happens
					error_log("NATHLOGS NEEDLE FOUND");
					$user_id = ( isset( $order_item['item_meta']['wcsg_recipient'] ) ) ? WCS_Gifting::get_order_item_recipient_user_id( $order_item ) : $order->customer_user;
					$user_unique_product_ids[ $user_id ][] = wcs_get_canonical_product_id( $order_item );
				}
			}`

does not work for Subscription Products with variations. 

@james-allan I see that you used a Subscription Product with variations, so I don't get how does my site behave differently... Should $order->get_items() return the product id instead of the variation id?

**Comment by EneHacheCe** [comment] 2016-10-06 16:50
Hey, I think I've found where it fails for me:
In WCSG_Memberships_Integration::get_user_unique_membership_access_granting_product_ids
$order->get_items() returns an array with the variation id
$all_access_granting_product_ids is an array with only the product id

So this:
foreach ( $order->get_items() as $order_item_id => $order_item ) {
if ( in_array( wcs_get_canonical_product_id( $order_item ), $all_access_granting_product_ids ) ) {
//this never happens
$user_id = ( isset( $order_item['item_meta']['wcsg_recipient'] ) ) ? WCS_Gifting::get_order_item_recipient_user_id( $order_item ) : $order->customer_user;
$user_unique_product_ids[ $user_id ][] = wcs_get_canonical_product_id( $order_item );
}
}

does not work for Subscription Products with variations.

@james-allan I see that you used a Subscription Product with variations, so I don't get how does my site behave differently...

**Comment by EneHacheCe** [comment] 2016-10-06 19:05
Ok! I've got it!
Until now id had set my membership plan as **"Grant Access to people who purchase:" My Product**. So, the membership wasn't created because **$plan->has_product( $item['variation_id'])** in **WC_Memberships::get_access_granting_purchased_product_ids** returns false.

So, to get the plugin to work I had to go to WooCommerce/Memberships/Membership Plans/My Plan and set "Grant Access to people who purchase:" to My Product, My Product Variation 1, My Product Variation 2...

I don't see why this problem appears when gifting and not when you buy a variable subscription for yourself. But anyway, that sloved it.

**Comment by james-allan** [comment] 2016-10-06 23:48
> Ok! I've got it!

Nice find!

I've been able to replicate this issue now. Gifting should grant memberships in the exact same way as WC Memberships so I'll take a deeper look and get that fixed up.

Thanks very much for debugging this @EneHacheCe 😄

**Comment by james-allan** [comment] 2016-10-07 01:20
@EneHacheCe I've just submitted a PR to fix that error. You can track it here: #171

**Comment by EneHacheCe** [comment] 2016-10-07 16:09
Great! Thanks! I'm glad it was useful!

**Closed** 2016-10-26 06:11 UTC
Labels: bug, hasPR
