### ISSUE TITLE
WooCommerce Subscriptions 2.0.13 compatibility?

### ISSUE THREAD

**Issue by RipcordSupport** [Prospress/woocommerce-subscriptions-gifting#137] opened 2016-04-26 19:31 UTC
I have upgraded to 2.0.13 and when I try to load the plugin for gifting, it automatically deactivates and breaks my activation for Subscriptions. 

It pops up a message that says I must have an activated version of WooCommerce Subscriptions, which I do. 

When I uninstall the gifting plugin, it goes back to working properly. 

<img width="1051" alt="screen shot 2016-04-26 at 3 29 36 pm" src="https://cloud.githubusercontent.com/assets/18293385/14831449/d76a1ae2-0bc3-11e6-8bc5-9400bf301d38.png">
<img width="1047" alt="screen shot 2016-04-26 at 3 29 15 pm" src="https://cloud.githubusercontent.com/assets/18293385/14831450/d76bd8fa-0bc3-11e6-8097-42b5feade32a.png">

**Comment by thenbrent** [comment] 2016-04-26 19:41
Hi @RipcordSupport sorry to hear you're having this issue. We're seeing a lot of tickets at the moment in the WooThemes support system with related issues. There appears to be some issue with the release or deployment of v2.0.13 causing the problem.

For now, can you please try:

1. logging into your web server via FTP
1. take a screenshot of your plugins folder to share with us (we want to see the folder name of the Subscriptions plugin)
1. change the folder/file name of the WooCommerce Subscriptions plugin to match the following folder/file name exactly: `woocommerce-subscriptions/woocommerce-subscriptions.php`

After changing the folder name (the file name should already be correct, but maybe not. You may need to reactivate the Subscriptions plugin.

Please let me know if this resolves the issue.

We're still working on diagnosing it, but suspect the issue is the folder name being changed during the update somehow.

**Comment by thenbrent** [comment] 2016-04-28 00:55
Hi @RipcordSupport this has been fixed now. It was an issue with the Subscriptions v2.0.13 zip file. If you change the folder name as mentioned in my previously reply, you should not longer have the issue with this or future updates. Thanks for the report. 😄

**Closed by thenbrent** 2016-04-28 00:55 UTC
