### ISSUE TITLE
Conflict?

### ISSUE THREAD

**Issue by panopticdesign** [Prospress/woocommerce-subscriptions-gifting#139] opened 2016-05-03 04:46 UTC
I installed the plugin but all I get is the following error ... "WooCommerce Subscriptions Gifting is inactive. WooCommerce Subscriptions Gifting requires the WooCommerce Subscriptions plugin to be active to work correctly. Please install & activate WooCommerce Subscriptions"

My version of WooCommerce Subscriptions is active but this plugin refuses to work. 

`
### WordPress Environment ###

Home URL: https://scudderassociation.org
Site URL: https://scudderassociation.org
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.35
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ 
						
							 No
Subscriptions Mode: ✔ 
						
							 Live
Zapier Integration - Active Feeds: ✔ 
						
							 4 active Zapier Feeds.
Zapier Integration - Cron Tasks: ✔ 
						
							 0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔ 
						
							 New Order to Lead
Zapier Feed #1 Webhook URL: ✔ 
						
							 https://zapier.com/hooks/catch/2t9rel/
Zapier Feed #1 Trigger: ✔ 
						
							 New Order
Zapier Feed #1 Test Result: ✔ 
						
							 Successfully sent sample data to https://zapier.com/hooks/catch/2t9rel/.
Zapier Feed #2 Name: ✔ 
						
							 New Customer to Contact
Zapier Feed #2 Webhook URL: ✔ 
						
							 https://zapier.com/hooks/catch/2t5mx3/
Zapier Feed #2 Trigger: ✔ 
						
							 New Customer
Zapier Feed #2 Test Result: ✔ 
						
							 Successfully sent sample data to https://zapier.com/hooks/catch/2t5mx3/.
Zapier Feed #3 Name: ✔ 
						
							 New Order to Contact
Zapier Feed #3 Webhook URL: ✔ 
						
							 https://zapier.com/hooks/catch/855051/3kk83x/
Zapier Feed #3 Trigger: ✔ 
						
							 New Order
Zapier Feed #3 Test Result: ✔ 
						
							 Successfully sent sample data to https://zapier.com/hooks/catch/855051/3kk83x/.
Zapier Feed #4 Name: ✔ 
						
							 New Line Item
Zapier Feed #4 Webhook URL: ✔ 
						
							 https://zapier.com/hooks/catch/855051/2nt8id/
Zapier Feed #4 Trigger: ✔ 
						
							 New Order
Zapier Feed #4 Test Result: ✔ 
						
							 Successfully sent sample data to https://zapier.com/hooks/catch/855051/2nt8id/.

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (52) ###

Gravity Forms: by rocketgenius – 1.9.18
BackupBuddy: by iThemes – 7.1.2.1
Billboard: by iThemes – 2.1.21
CSS Hero Inspector: by  – 1.3
CSSHero: by CssHero.org – 1.21
Envira Gallery - CSS Addon: by Thomas Griffin – 1.0.8
Envira Gallery - Fullscreen Addon: by Thomas Griffin – 1.0.6
Envira Gallery - Gallery Themes Addon: by Thomas Griffin – 1.1.0
Envira Gallery: by Thomas Griffin – 1.5.0.3
Envira Gallery - Pinterest Addon: by Thomas Griffin – 1.0.5
Envira Gallery - Slideshow Addon: by Thomas Griffin – 1.0.9
Envira Gallery - Supersize Addon: by Thomas Griffin – 1.1.2
Export Users to CSV: by Ulrich Sossou – 1.0.0
Genesis Club Pro: by Russell Jamieson – 4.35.1
Genesis Connect for WooCommerce: by StudioPress – 0.9.8
Genesis eNews Extended: by Brandon Kraft – 2.0.2
Genesis Layout Extras: by David Decker - DECKERWEB – 2.0.0
Genesis Printstyle Plus: by David Decker - DECKERWEB – 1.9.3
Genesis Simple Edits: by Nathan Rice – 2.1.4
Genesis Simple Headers: by wp.insider
vegasgeek – 2.4

Genesis Simple Hooks: by Nathan Rice – 2.1.2
Genesis Simple Sidebars: by Nathan Rice – 2.0.3
Genesis Title Toggle: by Bill Erickson – 1.7.0
Gravity Forms Salesforce Add-On: by Katz Web Services
Inc. – 3.1.2

Gravity Forms Zapier Add-on: by rocketgenius – 1.8
Groups WooCommerce: by itthinx – 1.9.5
Groups: by itthinx – 1.10.2
GTmetrix for WordPress: by GTmetrix – 0.4.1
Jetpack by WordPress.com: by Automattic – 4.0.2
Meta Slider - Pro Addon Pack: by Matcha Labs – 2.6.5
Meta Slider: by Matcha Labs – 3.3.6
Simple Social Icons: by Nathan Rice – 1.0.13
Soliloquy - Defaults Addon: by Thomas Griffin – 2.0.2
Soliloquy - Instagram Addon: by Thomas Griffin – 2.1.1
Soliloquy - Lightbox Addon: by Thomas Griffin – 2.2.8
Soliloquy - Pinterest Addon: by Thomas Griffin – 2.1.2
Soliloquy - Themes Addon: by Thomas Griffin – 2.1.6
Soliloquy - Thumbnails Addon: by Thomas Griffin – 2.2.6
Soliloquy: by Thomas Griffin – 2.4.4.3
Uber Grid: by Nikolay Karev – 2.1.2
WooCommerce Checkout Field Editor: by WooThemes – 1.4.10
WooCommerce Customer/Order CSV Import Suite: by WooThemes / SkyVerge – 2.9.0
WooCommerce Braintree Gateway: by WooThemes / SkyVerge – 3.2.0
WooCommerce - Gravity Forms Product Add-Ons: by WooThemes – 2.10.6
WooCommerce Memberships: by WooThemes / SkyVerge – 1.5.4
WooCommerce Sequential Order Numbers: by SkyVerge – 1.6.1
WooCommerce Smart Coupons: by WooThemes – 3.0.14
WooCommerce Subscriptions Gifting: by Prospress Inc. – 1.0
WooCommerce Subscriptions: by Prospress Inc. – 2.0.13
WooCommerce Zapier Integration: by OM4 – 1.5.3
WooCommerce: by WooThemes – 2.5.5
WooThemes Helper: by WooThemes – 1.6.2

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #7 - /shop/
Cart: #8 - /shop/cart/
Checkout: #9 - /shop/checkout/
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Education Pro Theme
Version: 3.0.0
Author URL: http://www.studiopress.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.2.7
Parent Theme Author URL: http://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: education-pro/woocommerce/emails/admin-cancelled-order.php
education-pro/woocommerce/emails/admin-new-order.php
education-pro/woocommerce/emails/customer-completed-order.php
education-pro/woocommerce/emails/customer-invoice.php
education-pro/woocommerce/emails/customer-new-account.php
education-pro/woocommerce/emails/customer-note.php
education-pro/woocommerce/emails/customer-processing-order.php
education-pro/woocommerce/emails/customer-refunded-order.php
education-pro/woocommerce/emails/customer-reset-password.php
education-pro/woocommerce/emails/email-addresses.php
education-pro/woocommerce/emails/email-footer.php
education-pro/woocommerce/emails/email-header.php
education-pro/woocommerce/emails/email-order-items.php
education-pro/woocommerce/emails/email-styles.php
education-pro/woocommerce/emails/plain/admin-cancelled-order.php
education-pro/woocommerce/emails/plain/admin-new-order.php
education-pro/woocommerce/emails/plain/customer-completed-order.php
education-pro/woocommerce/emails/plain/customer-invoice.php
education-pro/woocommerce/emails/plain/customer-new-account.php
education-pro/woocommerce/emails/plain/customer-note.php
education-pro/woocommerce/emails/plain/customer-processing-order.php
education-pro/woocommerce/emails/plain/customer-refunded-order.php
education-pro/woocommerce/emails/plain/customer-reset-password.php
education-pro/woocommerce/emails/plain/email-addresses.php
education-pro/woocommerce/emails/plain/email-order-items.php

### Braintree (Credit Card) ###

Environment: Sandbox
Tokenization Enabled: ✔
`

**Comment by thenbrent** [comment] 2016-05-03 05:19
Hi @panopticdesign this is most likely being caused by the issue discussed in #137. See my comment here https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/137#issuecomment-214862964 for a fix, and the comment below for an explanation.

I'll preemptively close this now, but if changing the Subscriptions folder name doesn't help, please reopen it and we'll investigate future.

Thanks for checking out Gifting and sorry for the rough start! 😄

**Closed by thenbrent** 2016-05-03 05:19 UTC
